ALTER TABLE users ADD COLUMN avatar_url VARCHAR(512) NULL;
ALTER TABLE customers ADD COLUMN image_url VARCHAR(512) NULL;
ALTER TABLE categories ADD COLUMN image_url VARCHAR(512) NULL;
ALTER TABLE products ADD COLUMN image_url VARCHAR(512) NULL;
