SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE order_items;
TRUNCATE TABLE payments;
TRUNCATE TABLE orders;
TRUNCATE TABLE customers;

SET FOREIGN_KEY_CHECKS = 1;

ALTER TABLE customers ADD COLUMN user_id INT NOT NULL UNIQUE;

ALTER TABLE customers
  ADD CONSTRAINT fk_customers_users FOREIGN KEY (user_id) REFERENCES users(id);
